version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=memodb
      - DB_SSLMODE=disable
      - TIMEZONE=UTC
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memodb
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: gcsfuse
    driver_opts:
      name: ${POSTGRES_DATA_DISK:-postgres-data} 