// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Memo struct {
	ID               int32        `json:"id"`
	DiscordUserID    string       `json:"discord_user_id"`
	DiscordChannelID string       `json:"discord_channel_id"`
	Content          string       `json:"content"`
	CreatedAt        sql.NullTime `json:"created_at"`
	RemindAt         time.Time    `json:"remind_at"`
	Sent             sql.NullBool `json:"sent"`
}

type User struct {
	UserID           string         `json:"user_id"`
	Username         string         `json:"username"`
	DiscordChannelID sql.NullString `json:"discord_channel_id"`
}
