// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CreateMemo(ctx context.Context, arg CreateMemoParams) (Memo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMemo(ctx context.Context, arg DeleteMemoParams) error
	GetMemo(ctx context.Context, id int32) (Memo, error)
	GetPendingReminders(ctx context.Context, remindAt time.Time) ([]Memo, error)
	GetReminderCounts(ctx context.Context, discordUserID string) ([]GetReminderCountsRow, error)
	GetUser(ctx context.Context, userID string) (User, error)
	ListAllPendingMemosInChannel(ctx context.Context, discordChannelID string) ([]Memo, error)
	ListPendingMemos(ctx context.Context, arg ListPendingMemosParams) ([]Memo, error)
	MarkMemoAsSent(ctx context.Context, id int32) error
	UpdateUserDiscordChannel(ctx context.Context, arg UpdateUserDiscordChannelParams) error
}

var _ Querier = (*Queries)(nil)
